version: "3"
services:
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_DB: stw_takehome
      POSTGRES_USER: stw_takehome
      POSTGRES_PASSWORD: stw_takehome
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db-init-sql:/docker-entrypoint-initdb.d
    ports:
      - 5551:5432
    restart: unless-stopped
  backend:
    build: ./backend
    ports:
      - 9099:9099
    volumes:
      - ./backend/src:/app/src
      - ./backend/tsconfig.json:/app/tsconfig.json
    environment:
      - PORT=9099
      - PGHOST=postgres
      - PGPORT=5432
  frontend:
    build: ./frontend
    ports:
      - 9098:9098
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/.env:/app/.env
      - ./frontend/index.html:/app/index.html
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/tsconfig.node.json:/app/tsconfig.node.json
volumes:
  postgres:
    external: false
