version: "3"
services:
  postgres:
    image: postgres:17.4
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: developer
    ports:
      - 5551:5432
    restart: unless-stopped
  dev_environment:
    build: "."
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 9099:9099
      - 9098:9098
    environment:
      - PORT=9099
      - PGHOST=postgres
      - PGPORT=5432
    depends_on:
      - postgres
volumes:
  postgres:
    external: false